#!/usr/bin/env python3

import random

def normal(mu):
    return int(round(random.normalvariate(mu,3),0))

for i in range (10):
    pm = random.randint(0,1)
    next_note = normal(2)
    if pm == 1:
        while next_note > 0:
            next_note = normal(2)
    else:
        while next_note <= 0:
            next_note = normal(-2)
    print(pm, next_note)

