#!/usr/bin/env python3

# music21 settings
from music21 import *
from matplotlib import *
environment.set('musicxmlPath', '/usr/bin/musescore')

# import needed gizmo funtions
from gizmo_funtions import return_part, stdin

# read from standard input
stdin_list = stdin()

# create stream
stream1 = stream.Stream()
for i in range(len(stdin_list)):
    current_note = (return_part(stdin_list,1)[i])
    current_duration = float((return_part(stdin_list,0)[i]))
    exec("note%s=note.Note('%s')" % (str(i),current_note))
    exec("note%s.duration.quarterLength = (%s)" % (str(i),current_duration))
    exec("stream1.append(note%s)" % (str(i)))

# open stream in predefinded environment
stream1.show()
