#!/usr/bin/env python3

# import needed gizmo funtions
from gizmo_funtions import *
from gizmo_transforming_functions import *

# read from standard input
stdin_list = stdin()



# write to standard output
gizmo_stdout(stdin_list)
